Invitation email template
atlp-rwanda/atlp-pulse-bn pull request #140
Opened 2023-08-28 00:32 UTC by Habihirwe

# PR Description

This PR updates the invitation email template.

# Description of tasks that were expected to be completed

- [x] Update the invitation email template to match the required.
- [x] Make sure all the link and redirections uses the correct urls.

### Functionality

1. Update your .env with the correct info
```
ADMIN_EMAIL=***** // the correct admin email you logged in with
ADMIN_PASS=****** // the correct admin password of the above email
REGISTER_FRONTEND_URL=***** // the correct register front-end page url (ex: http://localhost:3001/register) if using localhost on port 3001. the current register page is **/register**
```
2. Login as the admin and navigate to the trainees tab.
3. click the invite user button and insert the email of the trainee to be invited.
4. Lastly, check the email you provide on step 4 for the update template.

### PR Checklist:

- [x] Task 1

### Track PR

[Trello Link (#DP-62)](https://trello.com/c/SCpQyydc)

2023-08-29 16:08 UTC, ceelogre requested changes
Email subject should change.
<img width="1048" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-bn/assets/5022823/53320ef2-2a74-4953-a5a0-ca4158025338">

The image's source is not found.
<img width="1048" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-bn/assets/5022823/ca2c7d09-8649-4016-a4c5-5df2517f70a1">


The link at the bottom should be removed and the proper environment variable should be used.

2023-09-11 08:05 UTC, patsicko approved these changes

2023-09-11 08:37 UTC, AbdulKhaliq59 approved these changes
LGTM

2023-09-11 08:58 UTC, Luciefifi approved these changes

2023-09-13 04:07 UTC, Martha-Iradukunda approved these changes

2023-09-13 15:08 UTC, ceelogre approved these changes

2023-09-13 15:08 UTC, merged