fx(trainee): fix moving trainee error
atlp-rwanda/atlp-pulse-bn pull request #168
Opened 2023-10-09 09:42 UTC by rwamugema

### PR Description
Fix moving trainee error that says that the team has assigned ttl.
### Description of tasks that were expected to be completed

- Fix moving a trainee

### Functionality
Check if a member to be moved is a trainee not a ttl.
### How has this been tested?
Login as a coordinator and go trainee list and update one of the trainees from one cohort to another.
### PR Checklist:

- [ ] Fix trainee movement 

### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2023-10-11 14:22 UTC, NTElissa approved these changes

2023-10-11 15:13 UTC, Charlesntwari approved these changes

2023-10-11 19:44 UTC, mken1205 approved these changes

2023-10-12 13:27 UTC, ceelogre requested changes
I'd like to review this using a frontend deployment.

2024-03-22 10:26 UTC, ceelogre reviewed
Re-implemented.

2024-03-22 10:27 UTC, closed without merging