fix retrieving and reply tickets on admin panel
atlp-rwanda/atlp-pulse-bn pull request #198
Opened 2023-11-09 10:00 UTC by NdatimanaSamuel

### PR Description
when a user sent tickets ,admin was not able to view or to reply ticket which has been sent .
### Description of tasks that were expected to be completed
- admin can be able to retrieve tickets
- admin can be able to reply the ticket which has been sent 
### Functionality
added ability that allow admin to view and reply  tickets which has been sent 
### How has this been tested?

1. Cloned the repository using git clone **fix-retrieve/reply-tickets-adminpanel**
2. Installed necessary dependencies using npm install
3. Test by sending Tickets and login as admin check view tickets and be able to reply it 

### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)
![viewtickets](https://github.com/atlp-rwanda/atlp-pulse-bn/assets/77956577/b20ebd1c-907b-4def-ab64-6def6bd1bfd8)

2023-11-09 11:58 UTC, Charlesntwari approved these changes

2023-11-09 12:36 UTC, KAYITARES approved these changes

2023-11-09 16:09 UTC, ceelogre requested changes

2023-11-09 16:09 UTC, ceelogre commented on src/resolvers/attendance.resolvers.ts
> +      console.log('quick for demo ', trainees)
No log messages.

2023-11-09 16:09 UTC, ceelogre commented on src/resolvers/attendance.resolvers.ts
>          if (traineeIndex !== -1) {
See comment above.

2023-11-10 07:25 UTC, NdatimanaSamuel commented on src/resolvers/attendance.resolvers.ts
>          if (traineeIndex !== -1) {
> See comment above.

already solved !!!

2023-11-10 20:56 UTC, ceelogre approved these changes

2023-11-10 20:56 UTC, merged