#430 invitations Email Template
atlp-rwanda/atlp-pulse-bn pull request #247
Opened 2024-08-28 09:32 UTC by Yvan-David

### PR Description
Please include a brief description of the pull request you want to raise.

- implement styling on invitations email template

### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

1.  implement styling on invite User template

### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
### 430
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-09-02 07:30 UTC, niyobertin approved these changes
You can squash the commit to have at least 2 commit messages.

2024-09-02 15:34 UTC, ncutixavier reviewed
Make only necessary changes

2024-09-02 15:34 UTC, ncutixavier commented on .env.example
> +ADMIN_PASS=<****>
Why do you need this?

2024-09-03 14:17 UTC, YvetteNyibuka approved these changes

2024-09-03 14:32 UTC, Oliviier-dev approved these changes
LGTM

2024-09-03 15:04 UTC, ncutixavier requested changes

2024-09-03 15:04 UTC, ncutixavier commented on package.json
> +    "npm-force-resolutions": "^0.0.10",
Do we need this package?

2024-09-03 15:04 UTC, ncutixavier commented on src/index.ts
> +  const app = express() as any;;
Why do we need casting?

2024-09-03 22:42 UTC, ncutixavier approved these changes

2024-09-03 22:43 UTC, merged