feat(invitation):user with role of admin should invite user by role &…
atlp-rwanda/atlp-pulse-bn pull request #248
Opened 2024-08-29 10:10 UTC by niyobertin

### PR Description
Admin should be able to invite user to register on oragnisation by email and role 
### Description of tasks that were expected to be completed

- Inviting user by role and email
- role should be  trainee,coordinator,ttl or admin

### Functionality
This fuctionality involves creating post method to send invitation to the user by providing email and the role of user.  a user will reciev email requesting him or her to register to ivnited organisation.
### How has this been tested?

- clone this repo  then cd into it, opent it in your favolite text editor. run : npm install to install dependences,  npm run seed then npm run dev to start the server.
- login as admin then try to send any invitation by providing email and role.  for a success response the function return the invitation sent. 

Trello Link ([#421](https://github.com/atlp-rwanda/atlp-pulse-fn/issues/421))

2024-09-02 12:42 UTC, YvetteNyibuka approved these changes

2024-09-03 12:05 UTC, Yvan-David reviewed
Great Job

- Please remove unnecessary eslint format changes

- Please add some screenshots:

> 1. shows that the invitation email have been sent to users
> 2. after signup the users will have the roles given in excel not the default role(you may use the db to show it)

2024-09-03 14:26 UTC, YvetteNyibuka approved these changes

2024-09-03 15:02 UTC, mpanoathos approved these changes

2024-09-03 15:05 UTC, Sophie20202 approved these changes

2024-09-03 22:38 UTC, ncutixavier reviewed
I can see some unnecessary formatting, Please remove them

2024-09-03 22:40 UTC, ncutixavier requested changes

2024-09-03 22:40 UTC, ncutixavier commented on package.json
> +    "sinon": "^18.0.0",
Are you using this package? If not remove all unused packages

2024-09-04 07:29 UTC, ncutixavier approved these changes

2024-09-04 07:29 UTC, merged