ft(invitation): Invite users using an excel file
atlp-rwanda/atlp-pulse-bn pull request #257
Opened 2024-09-01 14:20 UTC by Oliviier-dev

### PR Description
Please include a brief description of the pull request you want to raise.
### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-09-03 12:01 UTC, Yvan-David reviewed
Great Job

Please add some screenshots

1. shows that the invitation email have been sent to users
2. after signup the users will have the roles given in excel not the default role(you may use the db to show it)

2024-09-04 08:29 UTC, niyobertin approved these changes

2024-09-04 08:42 UTC, Yvan-David approved these changes

2024-09-05 08:08 UTC, YvetteNyibuka approved these changes

2024-09-05 11:53 UTC, ncutixavier commented on src/resolvers/invitation.resolvers.ts
> +    async uploadInvitationFile(
Can you try refactoring this function? it is too long

2024-09-05 15:07 UTC, niyobertin approved these changes

2024-09-05 15:37 UTC, ncutixavier requested changes

2024-09-05 15:37 UTC, ncutixavier commented on src/resolvers/invitation.resolvers.ts
> +}
Validation should not be here

2024-09-05 15:37 UTC, ncutixavier commented on src/resolvers/invitation.resolvers.ts
> +        const role = (row as { role?: string }).role?.trim().toLowerCase()
This should not be here

2024-09-06 11:30 UTC, ncutixavier approved these changes

2024-09-06 11:30 UTC, merged