Ft coordinator notification
atlp-rwanda/atlp-pulse-bn pull request #259
Opened 2024-09-01 20:05 UTC by aimedivin

### PR Description
Please include a brief description of the pull request you want to raise.
### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-09-02 07:59 UTC, Calebgisa72 approved these changes

2024-09-05 22:01 UTC, elijahladdie requested changes

2024-09-05 22:01 UTC, elijahladdie commented on src/resolvers/ratingsResolvers.ts
> +          // }
Can your remove this comment if there are no longer needed

2024-09-05 22:01 UTC, elijahladdie commented on src/resolvers/ratingsResolvers.ts
> +      pushNotification(
remove these comments

2024-09-05 22:01 UTC, elijahladdie commented on src/utils/sendEmails.ts
> +  console.log("2",receiver)
remove this console

2024-09-06 06:24 UTC, aimedivin commented on src/resolvers/ratingsResolvers.ts
> +      pushNotification(
@elijahladdie Done

2024-09-06 07:03 UTC, pacifiquemboni approved these changes

2024-09-06 07:57 UTC, Ke-bean approved these changes
LGTM

2024-09-06 07:59 UTC, elijahladdie approved these changes
LGTM

2024-09-06 08:02 UTC, igorihimbazwe approved these changes

2024-09-06 08:12 UTC, MugemaneBertin2001 approved these changes
LGTM

2024-09-06 08:13 UTC, MugemaneBertin2001 commented
but remove these conflicts

2024-09-06 09:04 UTC, merged