Fix admin notification
atlp-rwanda/atlp-pulse-bn pull request #267
Opened 2024-09-05 06:33 UTC by hatfelicien

### PR Description
fixing in app notification on user admin for him to get notified whenever there's any action performed on the system
### Description of tasks that were expected to be completed
-Admin get notified each time a new session is created
-Admin get notified each time the trainee is dropped out of the program
### PR Checklist:
- [x] Task 1.
- [x] Task 2.
### Track PR

2024-09-06 07:16 UTC, aimedivin requested changes
@hatfelicien @rwemakevin 

Pls rebase and resolve conflicts

2024-09-06 08:05 UTC, igorihimbazwe requested changes
Rebase please

2024-09-10 05:31 UTC, MugemaneBertin2001 approved these changes
LGTM

2024-09-10 06:40 UTC, elijahladdie approved these changes

2024-09-10 07:15 UTC, amiparadis250 approved these changes

2024-09-10 07:40 UTC, aimedivin approved these changes

2024-09-10 07:46 UTC, igorihimbazwe approved these changes

2024-09-12 18:35 UTC, merged