#242-CRUD Operations for tickets
atlp-rwanda/atlp-pulse-bn pull request #287
Opened 2024-09-11 21:21 UTC by MugemaneBertin2001

2024-09-13 11:02 UTC, elijahladdie approved these changes

2024-09-16 09:36 UTC, amiparadis250 approved these changes

2024-09-16 09:40 UTC, pacifiquemboni approved these changes

2024-09-16 09:47 UTC, kanu-cast approved these changes

2024-09-16 11:27 UTC, Calebgisa72 approved these changes

2024-09-16 15:59 UTC, aimedivin approved these changes

2024-09-17 09:56 UTC, aimedivin requested changes
@amiparadis250 , @MugemaneBertin2001 this button for `New Tickets` displays on TTL side but  adding ticket does not work please make sure TTL can also add new ticket .

![image](https://github.com/user-attachments/assets/c74ca990-b446-4bc9-b2c7-411056a2565d)

2024-09-19 08:04 UTC, aimedivin approved these changes

2024-09-27 10:37 UTC, merged