Admin delete user
atlp-rwanda/atlp-pulse-bn pull request #300
Opened 2024-09-15 20:19 UTC by Christian-Ishimwe

### PR Description

### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-09-16 11:24 UTC, elijahladdie approved these changes

2024-09-17 20:38 UTC, aimedivin requested changes
@Christian-Ishimwe , @elijahladdie 
Work on requested changes on FE make sure you also updates BE

2024-09-20 08:13 UTC, pacifiquemboni approved these changes

2024-09-20 13:32 UTC, aimedivin approved these changes

2024-09-27 13:09 UTC, closed without merging