Mobile Reset Password
atlp-rwanda/atlp-pulse-bn pull request #332
Opened 2024-10-01 10:27 UTC by munezeromicha

### PR Description
This pull request introduces the functionality to allow users of the mobile app to reset their password, leveraging the same backend that serves web users. It integrates the 'Forgot Password' flow for the mobile app by sending a password reset email, handling user redirection to either the mobile app or the web depending on their platform.

### Description of tasks that were expected to be completed

 Implement password reset functionality in the mobile app.

-  Use the existing backend API that serves the web app for password reset.
-  Update the mobile app to handle deep linking for redirecting users back to the app after password reset.
-  Ensure email input is correctly handled within the mobile app.
-  Add error handling and validation to improve user experience during password reset.

### Functionality
The password reset flow now works as follows:

User requests a password reset from the mobile app.

1. A reset link is sent to the user's registered email.
2. Depending on the platform, the link either redirects the user to the web or back to the mobile app.
3. In the mobile app, the user is redirected to the 'Reset Password' screen to create a new password.

### How has this been tested?
Manual testing was conducted on both iOS and Android devices to ensure that:

- Users receive a password reset email.
- Deep linking works properly when the reset link is clicked, redirecting to the mobile app.
- The password reset screen functions as expected after redirect.
- Error messages display when invalid email addresses are entered.

2024-10-01 11:17 UTC, pacifiquemboni approved these changes

2024-10-01 11:55 UTC, fredshema requested changes

2024-10-01 11:55 UTC, fredshema commented on src/resolvers/userResolver.ts
> +        const deepLink = `${process.env.FRONTEND_LINK}/redirect-to-app/?path=/auth/forget/new-password&token=${newToken}`
The redirect path is `/redirect` not `/redirect-to-path`

2024-10-01 12:01 UTC, pacifiquemboni approved these changes

2024-10-01 12:02 UTC, fredshema approved these changes

2024-10-02 09:20 UTC, ncutixavier requested changes

2024-10-02 09:20 UTC, ncutixavier commented on src/resolvers/userResolver.ts
> +        const deepLink = `${process.env.FRONTEND_LINK}/redirect/?path=/auth/forget/new-password&token=${newToken}`
The auth route format is wrong. 

Example of possible routes:
- /auth/reset-password
- /auth/forgot-password

2024-10-02 16:03 UTC, ncutixavier approved these changes

2024-10-02 16:03 UTC, merged