Fix-sending-email-tickets
atlp-rwanda/atlp-pulse-bn pull request #353
Opened 2024-10-10 11:38 UTC by amiparadis250

# PR Description

Fixing all issues introduced in Tickets CRUD

# Description of tasks that were expected to be completed

.Email notification on every action 

# How has this been tested?

 simply you can go to this link https://metron-devpulse-git-fix-tickets-crud-metron.vercel.app/ then you login as TTl , Coordinator or Admin , then you can start manipulating

# Number of Commits
 1

# Screenshots (If appropriate)
![Screenshot 2024-10-10 133801](https://github.com/user-attachments/assets/058b8551-b2d2-46ce-a351-1400343c3a0e)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

2024-10-10 11:43 UTC, kanu-cast approved these changes

2024-10-11 06:00 UTC, igorihimbazwe approved these changes

2024-10-11 07:01 UTC, aimedivin requested changes
@amiparadis250 , please implement in-app notifications for when a ticket is updated or deleted. Currently, only email notifications are in place and inapp notification for ticket creation , so ensure that the in-app notification feature is added as well.

2024-10-11 10:36 UTC, amiparadis250 commented on src/resolvers/ticket.resolver.ts
> +            ticketOwner._id,
@aimedivin  know I am sending in-app notification for create and update

2024-10-11 10:58 UTC, igorihimbazwe approved these changes

2024-10-11 11:27 UTC, kanu-cast approved these changes

2024-10-17 11:59 UTC, Calebgisa72 approved these changes

2024-10-18 06:20 UTC, aimedivin approved these changes

2024-10-18 07:36 UTC, merged