fix: can't read undefinded of origanization while creating new organi…
atlp-rwanda/atlp-pulse-bn pull request #359
Opened 2024-10-14 21:36 UTC by elijahladdie

…zation

### PR Description
Please include a brief description of the pull request you want to raise.
### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-10-18 06:12 UTC, aimedivin requested changes

2024-10-18 06:12 UTC, aimedivin commented on src/resolvers/team.resolvers.ts
> +        console.log('>>>>>>>>>>>>>')
@elijahladdie remove these console.logs

2024-10-18 07:19 UTC, aimedivin requested changes

2024-10-18 07:19 UTC, aimedivin commented on src/context.ts
>    if (
@elijahladdie , also look it this

2024-10-20 14:58 UTC, amiparadis250 approved these changes

2024-11-19 10:22 UTC, elijahladdie commented
Solved in other PR

2024-11-19 10:22 UTC, closed without merging