#225 Fix-Remove ratings legacy feature
atlp-rwanda/atlp-pulse-bn pull request #372
Opened 2024-10-18 12:12 UTC by Bananayosostene

### PR Description
Please include a brief description of the pull request you want to raise.
### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-10-20 12:20 UTC, Tuyisenge2 approved these changes

2024-10-21 06:57 UTC, Tuyisenge2 approved these changes

2024-10-21 10:36 UTC, Tuyisenge2 approved these changes

2024-10-21 14:34 UTC, Dawaic6 approved these changes

2024-10-21 22:40 UTC, shema-surge requested changes
Please remove bodyQuality, bodyQuantity and bodyProfessional from the Ratings models

2024-10-22 15:03 UTC, shema-surge approved these changes

2024-10-22 15:05 UTC, JacquelineTuyisenge approved these changes

2024-10-29 14:42 UTC, merged