Added missing secret in env
atlp-rwanda/atlp-pulse-bn pull request #388
Opened 2024-10-25 15:45 UTC by MugemaneBertin2001

### PR Description
This fix adds missing SECRET variable in env during building docker image.

2024-10-25 18:33 UTC, niyobertin approved these changes

2024-10-27 07:59 UTC, JacquelineTuyisenge approved these changes

2024-10-28 14:51 UTC, elijahladdie approved these changes

2024-10-29 16:57 UTC, ceelogre requested changes

2024-10-29 16:57 UTC, ceelogre commented on .github/workflows/wss.yml
>        - develop
Should only run on push not PR.

2024-10-30 06:50 UTC, ceelogre approved these changes

2024-10-30 06:50 UTC, merged