Fix/missing secret env
atlp-rwanda/atlp-pulse-bn pull request #402
Opened 2024-10-30 08:45 UTC by MugemaneBertin2001

### PR Description
Please include a brief description of the pull request you want to raise.
### Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.
### Functionality
How does this works, add some information that maybe needed in testing
### How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
### PR Checklist:
- [ ] Task 1.
- [ ] Task 2.
- [ ] Task 3.
- [ ] Task n.
### Track PR
Trello Link (#DP-?)
### Screenshots (If appropriate)
(Images)

2024-10-30 09:27 UTC, niyobertin approved these changes

2024-10-30 10:30 UTC, YvetteNyibuka approved these changes

2024-10-30 11:57 UTC, ceelogre requested changes
The change is only needed in one middle for jwt.

2024-10-30 22:39 UTC, MugemaneBertin2001 commented
> The change is only needed in one middle for JWT.

@ceelogre you can take a look at it again.
and even try the beta .

2024-11-01 09:53 UTC, Salim-54 commented
Resolve the conflicts

2024-11-01 11:43 UTC, Salim-54 approved these changes

2024-11-11 15:52 UTC, ceelogre approved these changes

2024-11-11 15:52 UTC, merged