fix invite link
atlp-rwanda/atlp-pulse-bn pull request #93
Opened 2023-06-21 16:36 UTC by teerenzo

### PR Description
this is PR consist of bug fix of invite to be able to invite an organisation or user
### Description of tasks that were expected to be completed

An organisation Crud

### How has this been tested?
Using FE

### Track PR
Trello Link (#DP-https://trello.com/c/wB8v04xF)
### Screenshots (If appropriate)
(Images)

2023-06-22 15:50 UTC, Marthatwesi approved these changes

2023-06-22 16:08 UTC, UwaweTera approved these changes

2023-06-26 12:33 UTC, ceelogre requested changes

2023-06-26 12:33 UTC, ceelogre commented on src/resolvers/coordinatorResolvers.ts
> +        console.log(org?.name);
No log messages on PR.

2023-06-26 12:33 UTC, ceelogre commented on src/resolvers/userResolver.ts
> +
Why did we add commented out code?

2023-06-26 12:38 UTC, ceelogre approved these changes

2023-06-26 12:59 UTC, merged