Fix-Seeds
atlp-rwanda/atlp-pulse-bn pull request #94
Opened 2023-06-26 12:29 UTC by Marthatwesi

### PR Description
This PR fixes the Seeds on the backend
### Description of tasks that were expected to be completed
At least ten users are created for each of the coordinator and users account

### How has this been tested?
In the terminal of the project, run **npm run seed** and check the database to confirm if all seeds have been populated.

### Track PR
https://trello.com/c/GdxTzY4G/22-backend-seeds
### Screenshots (If appropriate)
(Images)

2023-06-28 18:59 UTC, UwaweTera requested changes, later dismissed
Make rebase

2023-06-29 14:22 UTC, UwaweTera approved these changes

2023-06-29 14:32 UTC, teerenzo approved these changes

2023-06-29 16:27 UTC, blackd44 approved these changes

2023-06-30 13:40 UTC, ceelogre approved these changes

2023-06-30 13:40 UTC, merged